"""portfolio_status.py — Scan all active projects, generate dashboard.

Reads PROJECT-CHARTER.md (or PROJECT STATE.md) from each active project,
aggregates status, and outputs a markdown dashboard.
"""
import os
from pathlib import Path
from datetime import datetime

PROJECTS_ROOT = Path(r'G:\My Drive\projects')
EXCLUDE = {'_shared', '_temp_uec', '.git'}

def find_active_projects():
    """Find project directories with mandatory docs."""
    projects = []
    if not PROJECTS_ROOT.exists():
        return projects

    for item in PROJECTS_ROOT.iterdir():
        if item.name in EXCLUDE or not item.is_dir():
            continue
        
        # Check for project markers
        charter = item / 'PROJECT-CHARTER.md'
        state = item / 'PROJECT STATE.md'
        readme = item / 'README.md'
        
        if readme.exists() or charter.exists() or state.exists():
            # Read charter/state for status
            status = 'Unknown'
            name = item.name
            last_updated = ''
            
            target_file = charter if charter.exists() else (state if state.exists() else readme)
            try:
                with open(target_file, 'r', encoding='utf-8', errors='ignore') as f:
                    content = f.read(2000)
                    for line in content.split('\n'):
                        if 'Status:' in line or '**Status:**' in line:
                            status = line.split(':', 1)[1].strip().strip('*').strip()
                        if 'Date:' in line or '**Date:**' in line:
                            last_updated = line.split(':', 1)[1].strip().strip('*').strip()
            except:
                pass

            # Count files
            try:
                file_count = len([f for f in item.rglob('*') if f.is_file() and '.git' not in str(f)])
            except:
                file_count = 0

            projects.append({
                'name': name,
                'path': str(item),
                'status': status,
                'last_updated': last_updated,
                'file_count': file_count
            })

    return projects


def generate_dashboard():
    """Generate portfolio status dashboard."""
    projects = find_active_projects()
    
    print('# PORTFOLIO STATUS DASHBOARD')
    print(f'**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M")}')
    print(f'**Active Projects:** {len(projects)}')
    print()

    if not projects:
        print('**No active projects found.**')
        return

    print('| Project | Status | Last Updated | Files |')
    print('|:--------|:-------|:-------------|:------|')
    for p in sorted(projects, key=lambda x: x['name']):
        print(f'| {p["name"]} | {p["status"]} | {p["last_updated"]} | {p["file_count"]} |')

    print()
    print('## Status Summary')
    statuses = {}
    for p in projects:
        s = p['status'].strip('[]')
        statuses[s] = statuses.get(s, 0) + 1
    for s, c in sorted(statuses.items()):
        print(f'- **{s}:** {c} project(s)')

    print()
    print('## Risks to Review')
    for p in projects:
        risk_path = Path(p['path']) / 'RISK-REGISTER.md'
        if risk_path.exists():
            try:
                with open(risk_path, 'r', encoding='utf-8', errors='ignore') as f:
                    content = f.read()
                active_risks = content.count('[Active')
                overdue = 'overdue' in content.lower()
                if active_risks > 0:
                    print(f'- **{p["name"]}:** {active_risks} active risk(s){" (OVERDUE REVIEW)" if overdue else ""}')
            except:
                pass

    print()
    print('---')
    print('*Generated by portfolio_status.py*')


if __name__ == '__main__':
    generate_dashboard()
